# Dockerfile
FROM nginx:latest

# Copy custom HTML content
COPY html/index.html /usr/share/nginx/html/index.html

# Copy custom NGINX configuration
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

